ArabicLearning/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArabicLearning.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ArabicLearning.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICoursesRepository coursesRepo;
        public CoursesController(ICoursesRepository Courses)
        {
            this.coursesRepo = Courses;
        }
        public IActionResult Index()
        {
            return View(coursesRepo.GetAllCourses());
        }
        
        [HttpGet("Courses/New")]
        public IActionResult NewCourses()
        {
            ViewData["Title"] = "New Courses";
            return View("~/Views/Courses/CategoriesTemplate.cshtml", coursesRepo.GetAllNew());
        }

        [HttpGet("Courses/Popular")]
        public IActionResult PopularCourses()
        {
            ViewData["Title"] = "Popular Courses";
            return View("~/Views/Courses/CategoriesTemplate.cshtml", coursesRepo.GetAllPopular());
        }


        [HttpGet("Courses/{type} Type")]
        public IActionResult CoursesOfType(string type)
        {
            ViewData["Title"] = type+" Courses";
            return View("~/Views/Courses/CategoriesTemplate.cshtml", coursesRepo.GetByType(type));
        }

        [HttpGet("Courses/{level} Level")]
        public IActionResult CoursesOfLevel(string level)
        {
            ViewData["Title"] = level+" Courses";
            System.Diagnostics.Debug.Write(coursesRepo.GetByLevel(level));
            return View("~/Views/Courses/CategoriesTemplate.cshtml", coursesRepo.GetByLevel(level));
        }

        [HttpGet("Courses/{id}/Detail")]
        public IActionResult CourseDetails(int id)
        {
            return View(coursesRepo.GetFullCourse(id));
        }

    }
}

ArabicLearning/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace ArabicLearning.Controllers
{
    [Authorize]
    public class ResourcesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ArabicLearning/Controllers/SocialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ArabicLearning.Controllers
{
    public class SocialController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ArabicLearning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArabicLearning Institute</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-nowrap" asp-area="" asp-controller="Home" asp-action="Index">ArabicLearning</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 flex-wrap">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Secured">Secured</a>
                        </li> -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resources" asp-action="Index">Resources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Social" asp-action="Index">Social</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item float-right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item float-right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item float-right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Sign up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ArabicLearning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <span>   |   </span>
            <a asp-area="" asp-controller="Images" asp-action="Images">Images</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>